entryPoints:
  web:
    address: ":80"

#http:
#  routers:
#    http-catchall:
#      rule: hostregexp(`{host:.+}`)
#      entrypoints:
#      - web
#      middlewares:
#      - redirect-to-https
#  middlewares:
#    redirect-to-https:
#      redirectScheme:
#        scheme: https
#        permanent: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  level: INFO

api:
  dashboard: true
