entryPoints:
  ep_traefik:
    address: ":8000" #https://github.com/traefik/traefik/issues/7545
  ep_jenkins:
    address: ":8080"

http:
 routers:
   http-catchall:
     rule: HostRegexp(`{subdomain:traefik}.localhost`)
     entrypoints:
     - ep_traefik

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  level: INFO

api:
  dashboard: true
